#!/bin/bash 
set -e

# Clone CRPropa3 3.2.1
git clone --depth 1 --branch 3.2.1 https://github.com/CRPropa/CRPropa3.git /tmp/CRPropa3

# Build and install
mkdir /tmp/CRPropa3/build
cd /tmp/CRPropa3/build

cmake .. \
    -DCMAKE_INSTALL_PREFIX=$HOME/.local \
    -DENABLE_PYTHON=ON \
    -DENABLE_SWIG_BUILTIN=ON \
    -DENABLE_FFTW3F=ON \
    -DENABLE_HDF5=ON \
    -DDOWNLOAD_DATA=ON

make -j$(nproc)
make install

# Cleanup source and build files to keep image size down
rm -rf /tmp/CRPropa3

# Move repo contents into a CRPropa/ subfolder so JupyterLab opens cleanly
# Set JupyterLab to open in the CRPropa folder

mkdir -p $HOME/.jupyter
cat >> $HOME/.jupyter/jupyter_server_config.py << 'EOF'
c.ServerApp.root_dir = '/home/jovyan/CRPropa'
EOF
cat >> $HOME/.jupyter/jupyter_notebook_config.py << 'EOF'
c.NotebookApp.notebook_dir = '/home/jovyan/CRPropa'
c.ServerApp.root_dir = '/home/jovyan/CRPropa'
EOF
